apiVersion: v1
kind: Service
metadata:
  name: shift-sched-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: shift-sched
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
